FROM amd64/debian

RUN apt-get update && \
    apt-get install -y apt-utils

RUN apt-get install -y default-jre-headless && \
    apt-get install -y wget && \
    apt-get install -y screen && \
    apt-get install -y git


RUN mkdir -p ~/minecraft && \
    cd ~/minecraft

RUN git clone https://github.com/MasonRiley/mc-docker.git

RUN ls

RUN cd mc-docker

RUN ls -la

RUN screen -d -m java -Xms1G -Xmx1G -jar server.jar nogui